package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1


import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer codecli;
     private String nomcli;
     private String prenomcli;
     private String mailcli;
     private String telcli;
     private Date datenai;
     private Boolean genrecli;
     private String mdpcli;
     private String objectif;
     private Set profilsportifs = new HashSet(0);
     private Set programmes = new HashSet(0);

    public Client() {
    }

    
    public Client(String nomcli, String prenomcli, String mailcli, String telcli, Date datenai, Boolean genrecli, String mdpcli, String objectif, Set profilsportifs, Set programmes) {
       this.nomcli = nomcli;
       this.prenomcli = prenomcli;
       this.mailcli = mailcli;
       this.telcli = telcli;
       this.datenai = datenai;
       this.genrecli = genrecli;
       this.mdpcli = mdpcli;
       this.objectif = objectif;
       this.profilsportifs = profilsportifs;
       this.programmes = programmes;
    }
    
    /**
     * 
     * @param nomcli
     * @param prenomCli
     * @param programmes 
     */
    public Client(String nomcli, String prenomcli, Set programmes){
        this.nomcli = nomcli;
        this.prenomcli = prenomcli;
        this.programmes = programmes;
    }
   
    public Integer getCodecli() {
        return this.codecli;
    }
    
    public void setCodecli(Integer codecli) {
        this.codecli = codecli;
    }
    public String getNomcli() {
        return this.nomcli;
    }
    
    public void setNomcli(String nomcli) {
        this.nomcli = nomcli;
    }
    public String getPrenomcli() {
        return this.prenomcli;
    }
    
    public void setPrenomcli(String prenomcli) {
        this.prenomcli = prenomcli;
    }
    public String getMailcli() {
        return this.mailcli;
    }
    
    public void setMailcli(String mailcli) {
        this.mailcli = mailcli;
    }
    public String getTelcli() {
        return this.telcli;
    }
    
    public void setTelcli(String telcli) {
        this.telcli = telcli;
    }
    public Date getDatenai() {
        return this.datenai;
    }
    
    public void setDatenai(Date datenai) {
        this.datenai = datenai;
    }
    public Boolean getGenrecli() {
        return this.genrecli;
    }
    
    public void setGenrecli(Boolean genrecli) {
        this.genrecli = genrecli;
    }
    public String getMdpcli() {
        return this.mdpcli;
    }
    
    public void setMdpcli(String mdpcli) {
        this.mdpcli = mdpcli;
    }
    public String getObjectif() {
        return this.objectif;
    }
    
    public void setObjectif(String objectif) {
        this.objectif = objectif;
    }
    public Set getProfilsportifs() {
        return this.profilsportifs;
    }
    
    public void setProfilsportifs(Set profilsportifs) {
        this.profilsportifs = profilsportifs;
    }
    public Set getProgrammes() {
        return this.programmes;
    }
    
    public void setProgrammes(Set programmes) {
        this.programmes = programmes;
    }

    public void addProgramme(Programme programme)
    {
        this.programmes.add(programme);
    }

    public int getAge(){
        int year = Calendar.getInstance().get(Calendar.YEAR)-1900;
        return (int)year-this.datenai.getYear();
    }


}


