package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Coach generated by hbm2java
 */
public class Coach  implements java.io.Serializable {


     private Integer codec;
     private String nomc;
     private String prenomc;
     private String mailc;
     private String mailadmin;
     private String telc;
     private String mdpc;
     private Set programmes = new HashSet(0);

    public Coach() {
    }

    public Coach(String nomc, String prenomc, String mailc, String mailadmin, String telc, String mdpc, Set programmes) {
       this.nomc = nomc;
       this.prenomc = prenomc;
       this.mailc = mailc;
       this.mailadmin = mailadmin;
       this.telc = telc;
       this.mdpc = mdpc;
       this.programmes = programmes;
    }
   
    public Integer getCodec() {
        return this.codec;
    }
    
    public void setCodec(Integer codec) {
        this.codec = codec;
    }
    public String getNomc() {
        return this.nomc;
    }
    
    public void setNomc(String nomc) {
        this.nomc = nomc;
    }
    public String getPrenomc() {
        return this.prenomc;
    }
    
    public void setPrenomc(String prenomc) {
        this.prenomc = prenomc;
    }
    public String getMailc() {
        return this.mailc;
    }
    
    public void setMailc(String mailc) {
        this.mailc = mailc;
    }
    public String getMailadmin() {
        return this.mailadmin;
    }
    
    public void setMailadmin(String mailadmin) {
        this.mailadmin = mailadmin;
    }
    public String getTelc() {
        return this.telc;
    }
    
    public void setTelc(String telc) {
        this.telc = telc;
    }
    public String getMdpc() {
        return this.mdpc;
    }
    
    public void setMdpc(String mdpc) {
        this.mdpc = mdpc;
    }
    public Set getProgrammes() {
        return this.programmes;
    }
    
    public void setProgrammes(Set programmes) {
        this.programmes = programmes;
    }




}


