package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exercicetype generated by hbm2java
 */
public class Exercicetype  implements java.io.Serializable {


     private Integer codeet;
     private String nomet;
     private String descriptione;
     private String lienmedia;
     private String tipsrep;
     private String tipsexo;
     private String materiel;
     private String objectif;
     private Set exercices = new HashSet(0);
     private Set predefinirexos = new HashSet(0);

    public Exercicetype() {
    }

    public Exercicetype(String nomet, String descriptione, String lienmedia, String tipsrep, String tipsexo, String materiel, String objectif) {
        this.nomet = nomet;
        this.descriptione = descriptione;
        this.lienmedia = lienmedia;
        this.tipsrep = tipsrep;
        this.tipsexo = tipsexo;
        this.materiel = materiel;
        this.objectif = objectif;
    }

    
    public Exercicetype(String nomet, String descriptione, String lienmedia, String tipsrep, String tipsexo, String materiel, String objectif, Set exercices, Set predefinirexos) {
       this.nomet = nomet;
       this.descriptione = descriptione;
       this.lienmedia = lienmedia;
       this.tipsrep = tipsrep;
       this.tipsexo = tipsexo;
       this.materiel = materiel;
       this.objectif = objectif;
       this.exercices = exercices;
       this.predefinirexos = predefinirexos;
    }
   
    public Integer getCodeet() {
        return this.codeet;
    }
    
    public void setCodeet(Integer codeet) {
        this.codeet = codeet;
    }
    public String getNomet() {
        return this.nomet;
    }
    
    public void setNomet(String nomet) {
        this.nomet = nomet;
    }
    public String getDescriptione() {
        return this.descriptione;
    }
    
    public void setDescriptione(String descriptione) {
        this.descriptione = descriptione;
    }
    public String getLienmedia() {
        return this.lienmedia;
    }
    
    public void setLienmedia(String lienmedia) {
        this.lienmedia = lienmedia;
    }
    public String getTipsrep() {
        return this.tipsrep;
    }
    
    public void setTipsrep(String tipsrep) {
        this.tipsrep = tipsrep;
    }
    public String getTipsexo() {
        return this.tipsexo;
    }
    
    public void setTipsexo(String tipsexo) {
        this.tipsexo = tipsexo;
    }
    public String getMateriel() {
        return this.materiel;
    }
    
    public void setMateriel(String materiel) {
        this.materiel = materiel;
    }
    public String getObjectif() {
        return this.objectif;
    }
    
    public void setObjectif(String objectif) {
        this.objectif = objectif;
    }
    public Set getExercices() {
        return this.exercices;
    }
    
    public void setExercices(Set exercices) {
        this.exercices = exercices;
    }
    public Set getPredefinirexos() {
        return this.predefinirexos;
    }
    
    public void setPredefinirexos(Set predefinirexos) {
        this.predefinirexos = predefinirexos;
    }




}


