package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exercice generated by hbm2java
 */
public class Exercice  implements java.io.Serializable {


     private Integer codee;
     private Exercicetype exercicetype;
     private Seance seance;
     private Integer ordre;
     private Integer nbrep;
     private Integer nbserie;
     private Integer tempsexo;
     private Integer tempsreposserie;
     private Integer tempsreposexo;
     private Set resultatexos = new HashSet(0);

    public Exercice() {
    }

	
    public Exercice(Exercicetype exercicetype, Seance seance) {
        this.exercicetype = exercicetype;
        this.seance = seance;
    }
    public Exercice(Exercicetype exercicetype, Seance seance, Integer ordre, Integer nbrep, Integer nbserie, Integer tempsexo, Integer tempsreposserie, Integer tempsreposexo, Set resultatexos) {
       this.exercicetype = exercicetype;
       this.seance = seance;
       this.ordre = ordre;
       this.nbrep = nbrep;
       this.nbserie = nbserie;
       this.tempsexo = tempsexo;
       this.tempsreposserie = tempsreposserie;
       this.tempsreposexo = tempsreposexo;
       this.resultatexos = resultatexos;
    }
   
    public Integer getCodee() {
        return this.codee;
    }
    
    public void setCodee(Integer codee) {
        this.codee = codee;
    }
    public Exercicetype getExercicetype() {
        return this.exercicetype;
    }
    
    public void setExercicetype(Exercicetype exercicetype) {
        this.exercicetype = exercicetype;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public Integer getOrdre() {
        return this.ordre;
    }
    
    public void setOrdre(Integer ordre) {
        this.ordre = ordre;
    }
    public Integer getNbrep() {
        return this.nbrep;
    }
    
    public void setNbrep(Integer nbrep) {
        this.nbrep = nbrep;
    }
    public Integer getNbserie() {
        return this.nbserie;
    }
    
    public void setNbserie(Integer nbserie) {
        this.nbserie = nbserie;
    }
    public Integer getTempsexo() {
        return this.tempsexo;
    }
    
    public void setTempsexo(Integer tempsexo) {
        this.tempsexo = tempsexo;
    }
    public Integer getTempsreposserie() {
        return this.tempsreposserie;
    }
    
    public void setTempsreposserie(Integer tempsreposserie) {
        this.tempsreposserie = tempsreposserie;
    }
    public Integer getTempsreposexo() {
        return this.tempsreposexo;
    }
    
    public void setTempsreposexo(Integer tempsreposexo) {
        this.tempsreposexo = tempsreposexo;
    }
    public Set getResultatexos() {
        return this.resultatexos;
    }
    
    public void setResultatexos(Set resultatexos) {
        this.resultatexos = resultatexos;
    }




}


