package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1



/**
 * PredefinirseanceId generated by hbm2java
 */
public class PredefinirseanceId  implements java.io.Serializable {


     private int codept;
     private int codest;
     private int ordreexo;
     private int numsemaine;

    public PredefinirseanceId() {
    }

    public PredefinirseanceId(int codept, int codest, int ordreexo, int numsemaine) {
       this.codept = codept;
       this.codest = codest;
       this.ordreexo = ordreexo;
       this.numsemaine = numsemaine;
    }
   
    public int getCodept() {
        return this.codept;
    }
    
    public void setCodept(int codept) {
        this.codept = codept;
    }
    public int getCodest() {
        return this.codest;
    }
    
    public void setCodest(int codest) {
        this.codest = codest;
    }
    public int getOrdreexo() {
        return this.ordreexo;
    }
    
    public void setOrdreexo(int ordreexo) {
        this.ordreexo = ordreexo;
    }
    public int getNumsemaine() {
        return this.numsemaine;
    }
    
    public void setNumsemaine(int numsemaine) {
        this.numsemaine = numsemaine;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PredefinirseanceId) ) return false;
		 PredefinirseanceId castOther = ( PredefinirseanceId ) other; 
         
		 return (this.getCodept()==castOther.getCodept())
 && (this.getCodest()==castOther.getCodest())
 && (this.getOrdreexo()==castOther.getOrdreexo())
 && (this.getNumsemaine()==castOther.getNumsemaine());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodept();
         result = 37 * result + this.getCodest();
         result = 37 * result + this.getOrdreexo();
         result = 37 * result + this.getNumsemaine();
         return result;
   }   


}


