package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1



/**
 * Predefinirexo generated by hbm2java
 */
public class Predefinirexo  implements java.io.Serializable {


     private PredefinirexoId id;
     private Exercicetype exercicetype;
     private Seancetype seancetype;
     private Integer nbrep;
     private Integer nbserie;
     private Integer tempsexo;
     private Integer tempsreposserie;
     private Integer tempsreposexo;

    public Predefinirexo() {
    }

	
    public Predefinirexo(PredefinirexoId id, Exercicetype exercicetype, Seancetype seancetype) {
        this.id = id;
        this.exercicetype = exercicetype;
        this.seancetype = seancetype;
    }
    public Predefinirexo(PredefinirexoId id, Exercicetype exercicetype, Seancetype seancetype, Integer nbrep, Integer nbserie, Integer tempsexo, Integer tempsreposserie, Integer tempsreposexo) {
       this.id = id;
       this.exercicetype = exercicetype;
       this.seancetype = seancetype;
       this.nbrep = nbrep;
       this.nbserie = nbserie;
       this.tempsexo = tempsexo;
       this.tempsreposserie = tempsreposserie;
       this.tempsreposexo = tempsreposexo;
    }
   
    public PredefinirexoId getId() {
        return this.id;
    }
    
    public void setId(PredefinirexoId id) {
        this.id = id;
    }
    public Exercicetype getExercicetype() {
        return this.exercicetype;
    }
    
    public void setExercicetype(Exercicetype exercicetype) {
        this.exercicetype = exercicetype;
    }
    public Seancetype getSeancetype() {
        return this.seancetype;
    }
    
    public void setSeancetype(Seancetype seancetype) {
        this.seancetype = seancetype;
    }
    public Integer getNbrep() {
        return this.nbrep;
    }
    
    public void setNbrep(Integer nbrep) {
        this.nbrep = nbrep;
    }
    public Integer getNbserie() {
        return this.nbserie;
    }
    
    public void setNbserie(Integer nbserie) {
        this.nbserie = nbserie;
    }
    public Integer getTempsexo() {
        return this.tempsexo;
    }
    
    public void setTempsexo(Integer tempsexo) {
        this.tempsexo = tempsexo;
    }
    public Integer getTempsreposserie() {
        return this.tempsreposserie;
    }
    
    public void setTempsreposserie(Integer tempsreposserie) {
        this.tempsreposserie = tempsreposserie;
    }
    public Integer getTempsreposexo() {
        return this.tempsreposexo;
    }
    
    public void setTempsreposexo(Integer tempsreposexo) {
        this.tempsreposexo = tempsreposexo;
    }




}


