package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1



/**
 * Predefinirseance generated by hbm2java
 */
public class Predefinirseance  implements java.io.Serializable {


     private PredefinirseanceId id;
     private Programmetype programmetype;
     private Seancetype seancetype;

    public Predefinirseance() {
    }

    public Predefinirseance(PredefinirseanceId id, Programmetype programmetype, Seancetype seancetype) {
       this.id = id;
       this.programmetype = programmetype;
       this.seancetype = seancetype;
    }
   
    public PredefinirseanceId getId() {
        return this.id;
    }
    
    public void setId(PredefinirseanceId id) {
        this.id = id;
    }
    public Programmetype getProgrammetype() {
        return this.programmetype;
    }
    
    public void setProgrammetype(Programmetype programmetype) {
        this.programmetype = programmetype;
    }
    public Seancetype getSeancetype() {
        return this.seancetype;
    }
    
    public void setSeancetype(Seancetype seancetype) {
        this.seancetype = seancetype;
    }




}


