package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1



/**
 * PredefinirexoId generated by hbm2java
 */
public class PredefinirexoId  implements java.io.Serializable {


     private int codeet;
     private int codest;
     private int ordree;

    public PredefinirexoId() {
    }

    public PredefinirexoId(int codeet, int codest, int ordree) {
       this.codeet = codeet;
       this.codest = codest;
       this.ordree = ordree;
    }
   
    public int getCodeet() {
        return this.codeet;
    }
    
    public void setCodeet(int codeet) {
        this.codeet = codeet;
    }
    public int getCodest() {
        return this.codest;
    }
    
    public void setCodest(int codest) {
        this.codest = codest;
    }
    public int getOrdree() {
        return this.ordree;
    }
    
    public void setOrdree(int ordree) {
        this.ordree = ordree;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PredefinirexoId) ) return false;
		 PredefinirexoId castOther = ( PredefinirexoId ) other; 
         
		 return (this.getCodeet()==castOther.getCodeet())
 && (this.getCodest()==castOther.getCodest())
 && (this.getOrdree()==castOther.getOrdree());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodeet();
         result = 37 * result + this.getCodest();
         result = 37 * result + this.getOrdree();
         return result;
   }   


}


