package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1



/**
 * Profilsportif generated by hbm2java
 */
public class Profilsportif  implements java.io.Serializable {


     private Integer codeprofil;
     private Client client;
     private Float poids;
     private Integer bras;
     private Integer taille;
     private Integer hanches;
     private Integer cuisses;
     private Integer poitrine;
     private Boolean handicap;

    public Profilsportif() {
    }

	
    public Profilsportif(Client client) {
        this.client = client;
    }
    public Profilsportif(Client client, Float poids, Integer bras, Integer taille, Integer hanches, Integer cuisses, Integer poitrine, Boolean handicap) {
       this.client = client;
       this.poids = poids;
       this.bras = bras;
       this.taille = taille;
       this.hanches = hanches;
       this.cuisses = cuisses;
       this.poitrine = poitrine;
       this.handicap = handicap;
    }
   
    public Integer getCodeprofil() {
        return this.codeprofil;
    }
    
    public void setCodeprofil(Integer codeprofil) {
        this.codeprofil = codeprofil;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Float getPoids() {
        return this.poids;
    }
    
    public void setPoids(Float poids) {
        this.poids = poids;
    }
    public Integer getBras() {
        return this.bras;
    }
    
    public void setBras(Integer bras) {
        this.bras = bras;
    }
    public Integer getTaille() {
        return this.taille;
    }
    
    public void setTaille(Integer taille) {
        this.taille = taille;
    }
    public Integer getHanches() {
        return this.hanches;
    }
    
    public void setHanches(Integer hanches) {
        this.hanches = hanches;
    }
    public Integer getCuisses() {
        return this.cuisses;
    }
    
    public void setCuisses(Integer cuisses) {
        this.cuisses = cuisses;
    }
    public Integer getPoitrine() {
        return this.poitrine;
    }
    
    public void setPoitrine(Integer poitrine) {
        this.poitrine = poitrine;
    }
    public String getHandicap() {
        if(this.handicap == true){
            return "Oui";
        }
        return "Non";
    }
    
    public void setHandicap(Boolean handicap) {
        this.handicap = handicap;
    }




}


