package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Programme generated by hbm2java
 */
public class Programme  implements java.io.Serializable {


     private Integer codep;
     private Client client;
     private Coach coach;
     private Programmetype programmetype;
     private Date datedebut;
     private Set seances = new HashSet(0);

    public Programme() {
    }

	
    public Programme(Client client, Coach coach, Programmetype programmetype) {
        this.client = client;
        this.coach = coach;
        this.programmetype = programmetype;
    }
    public Programme(Client client, Coach coach, Programmetype programmetype, Date datedebut, Set seances) {
       this.client = client;
       this.coach = coach;
       this.programmetype = programmetype;
       this.datedebut = datedebut;
       this.seances = seances;
    }
   
    public Integer getCodep() {
        return this.codep;
    }
    
    public void setCodep(Integer codep) {
        this.codep = codep;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Coach getCoach() {
        return this.coach;
    }
    
    public void setCoach(Coach coach) {
        this.coach = coach;
    }
    public Programmetype getProgrammetype() {
        return this.programmetype;
    }
    
    public void setProgrammetype(Programmetype programmetype) {
        this.programmetype = programmetype;
    }
    public Date getDatedebut() {
        return this.datedebut;
    }
    
    public void setDatedebut(Date datedebut) {
        this.datedebut = datedebut;
    }
    public Set getSeances() {
        return this.seances;
    }
    
    public void setSeances(Set seances) {
        this.seances = seances;
    }




}


