package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Programmetype generated by hbm2java
 */
public class Programmetype  implements java.io.Serializable {


     private Integer codept;
     private String nomp;
     private String descriptionp;
     private Set predefinirseances = new HashSet(0);
     private Set programmes = new HashSet(0);

    public Programmetype() {
    }

    public Programmetype(String nomp, String descriptionp, Set predefinirseances, Set programmes) {
       this.nomp = nomp;
       this.descriptionp = descriptionp;
       this.predefinirseances = predefinirseances;
       this.programmes = programmes;
    }
    
    public Programmetype(String nomp, String desp) {
        this.nomp = nomp;
        this.descriptionp = desp;
    }

   
    public Integer getCodept() {
        return this.codept;
    }
    
    public void setCodept(Integer codept) {
        this.codept = codept;
    }
    public String getNomp() {
        return this.nomp;
    }
    
    public void setNomp(String nomp) {
        this.nomp = nomp;
    }
    public String getDescriptionp() {
        return this.descriptionp;
    }
    
    public void setDescriptionp(String descriptionp) {
        this.descriptionp = descriptionp;
    }
    public Set getPredefinirseances() {
        return this.predefinirseances;
    }
    
    public void setPredefinirseances(Set predefinirseances) {
        this.predefinirseances = predefinirseances;
    }
    public Set getProgrammes() {
        return this.programmes;
    }
    
    public void setProgrammes(Set programmes) {
        this.programmes = programmes;
    }
    
    public void addProgramme(Programme programme)
    {
        this.programmes.add(programme);
    }




}


