package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1



/**
 * Resultatseance generated by hbm2java
 */
public class Resultatseance  implements java.io.Serializable {


     private Integer coderesseance;
     private Seance seance;
     private Integer durees;
     private String commentairecli;
     private Boolean validationparcoach;
     private Float poids;
     private Integer fcrepos;
     private Integer fcmax;
     private Integer fccondition1;
     private Integer fccondition2;
     private Integer fccondition3;
     private Integer bras;
     private Integer poitrine;
     private Integer taille;
     private Integer hanches;
     private Integer cuisses;

    public Resultatseance() {
    }

	
    public Resultatseance(Seance seance) {
        this.seance = seance;
    }
    public Resultatseance(Seance seance, Integer durees, String commentairecli, Boolean validationparcoach, Float poids, Integer fcrepos, Integer fcmax, Integer fccondition1, Integer fccondition2, Integer fccondition3, Integer bras, Integer poitrine, Integer taille, Integer hanches, Integer cuisses) {
       this.seance = seance;
       this.durees = durees;
       this.commentairecli = commentairecli;
       this.validationparcoach = validationparcoach;
       this.poids = poids;
       this.fcrepos = fcrepos;
       this.fcmax = fcmax;
       this.fccondition1 = fccondition1;
       this.fccondition2 = fccondition2;
       this.fccondition3 = fccondition3;
       this.bras = bras;
       this.poitrine = poitrine;
       this.taille = taille;
       this.hanches = hanches;
       this.cuisses = cuisses;
    }
   
    public Integer getCoderesseance() {
        return this.coderesseance;
    }
    
    public void setCoderesseance(Integer coderesseance) {
        this.coderesseance = coderesseance;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public Integer getDurees() {
        return this.durees;
    }
    
    public void setDurees(Integer durees) {
        this.durees = durees;
    }
    public String getCommentairecli() {
        return this.commentairecli;
    }
    
    public void setCommentairecli(String commentairecli) {
        this.commentairecli = commentairecli;
    }
    public Boolean getValidationparcoach() {
        return this.validationparcoach;
    }
    
    public void setValidationparcoach(Boolean validationparcoach) {
        this.validationparcoach = validationparcoach;
    }
    public Float getPoids() {
        return this.poids;
    }
    
    public void setPoids(Float poids) {
        this.poids = poids;
    }
    public Integer getFcrepos() {
        return this.fcrepos;
    }
    
    public void setFcrepos(Integer fcrepos) {
        this.fcrepos = fcrepos;
    }
    public Integer getFcmax() {
        return this.fcmax;
    }
    
    public void setFcmax(Integer fcmax) {
        this.fcmax = fcmax;
    }
    public Integer getFccondition1() {
        return this.fccondition1;
    }
    
    public void setFccondition1(Integer fccondition1) {
        this.fccondition1 = fccondition1;
    }
    public Integer getFccondition2() {
        return this.fccondition2;
    }
    
    public void setFccondition2(Integer fccondition2) {
        this.fccondition2 = fccondition2;
    }
    public Integer getFccondition3() {
        return this.fccondition3;
    }
    
    public void setFccondition3(Integer fccondition3) {
        this.fccondition3 = fccondition3;
    }
    public Integer getBras() {
        return this.bras;
    }
    
    public void setBras(Integer bras) {
        this.bras = bras;
    }
    public Integer getPoitrine() {
        return this.poitrine;
    }
    
    public void setPoitrine(Integer poitrine) {
        this.poitrine = poitrine;
    }
    public Integer getTaille() {
        return this.taille;
    }
    
    public void setTaille(Integer taille) {
        this.taille = taille;
    }
    public Integer getHanches() {
        return this.hanches;
    }
    
    public void setHanches(Integer hanches) {
        this.hanches = hanches;
    }
    public Integer getCuisses() {
        return this.cuisses;
    }
    
    public void setCuisses(Integer cuisses) {
        this.cuisses = cuisses;
    }




}


