package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1



/**
 * Resultatexo generated by hbm2java
 */
public class Resultatexo  implements java.io.Serializable {


     private Integer coderesexo;
     private Exercice exercice;
     private Integer maxtemps;
     private Integer maxrep;
     private Boolean appreciation;

    public Resultatexo() {
    }

	
    public Resultatexo(Exercice exercice) {
        this.exercice = exercice;
    }
    public Resultatexo(Exercice exercice, Integer maxtemps, Integer maxrep, Boolean appreciation) {
       this.exercice = exercice;
       this.maxtemps = maxtemps;
       this.maxrep = maxrep;
       this.appreciation = appreciation;
    }
   
    public Integer getCoderesexo() {
        return this.coderesexo;
    }
    
    public void setCoderesexo(Integer coderesexo) {
        this.coderesexo = coderesexo;
    }
    public Exercice getExercice() {
        return this.exercice;
    }
    
    public void setExercice(Exercice exercice) {
        this.exercice = exercice;
    }
    public Integer getMaxtemps() {
        return this.maxtemps;
    }
    
    public void setMaxtemps(Integer maxtemps) {
        this.maxtemps = maxtemps;
    }
    public Integer getMaxrep() {
        return this.maxrep;
    }
    
    public void setMaxrep(Integer maxrep) {
        this.maxrep = maxrep;
    }
    public Boolean getAppreciation() {
        return this.appreciation;
    }
    
    public void setAppreciation(Boolean appreciation) {
        this.appreciation = appreciation;
    }




}


