package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seance generated by hbm2java
 */
public class Seance  implements java.io.Serializable {


     private Integer codes;
     private Programme programme;
     private Seancetype seancetype;
     private Integer semaines;
     private Integer ordres;
     private Set resultatseances = new HashSet(0);
     private Set exercices = new HashSet(0);

    public Seance() {
    }

	
    public Seance(Programme programme, Seancetype seancetype) {
        this.programme = programme;
        this.seancetype = seancetype;
    }
    public Seance(Programme programme, Seancetype seancetype, Integer semaines, Integer ordres, Set resultatseances, Set exercices) {
       this.programme = programme;
       this.seancetype = seancetype;
       this.semaines = semaines;
       this.ordres = ordres;
       this.resultatseances = resultatseances;
       this.exercices = exercices;
    }
   
    public Integer getCodes() {
        return this.codes;
    }
    
    public void setCodes(Integer codes) {
        this.codes = codes;
    }
    public Programme getProgramme() {
        return this.programme;
    }
    
    public void setProgramme(Programme programme) {
        this.programme = programme;
    }
    public Seancetype getSeancetype() {
        return this.seancetype;
    }
    
    public void setSeancetype(Seancetype seancetype) {
        this.seancetype = seancetype;
    }
    public Integer getSemaines() {
        return this.semaines;
    }
    
    public void setSemaines(Integer semaines) {
        this.semaines = semaines;
    }
    public Integer getOrdres() {
        return this.ordres;
    }
    
    public void setOrdres(Integer ordres) {
        this.ordres = ordres;
    }
    public Set getResultatseances() {
        return this.resultatseances;
    }
    
    public void setResultatseances(Set resultatseances) {
        this.resultatseances = resultatseances;
    }
    public Set getExercices() {
        return this.exercices;
    }
    
    public void setExercices(Set exercices) {
        this.exercices = exercices;
    }




}


