package db;
// Generated 27 mars 2019 11:38:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seancetype generated by hbm2java
 */
public class Seancetype  implements java.io.Serializable {


     private Integer codest;
     private String noms;
     private String descriptions;
     private Set seances = new HashSet(0);
     private Set predefinirseances = new HashSet(0);
     private Set predefinirexos = new HashSet(0);

    public Seancetype() {
    }
    
    public Seancetype(String noms, String descriptions) {
       this.noms = noms;
       this.descriptions = descriptions;
    }

    public Seancetype(String noms, String descriptions, Set seances, Set predefinirseances, Set predefinirexos) {
       this.noms = noms;
       this.descriptions = descriptions;
       this.seances = seances;
       this.predefinirseances = predefinirseances;
       this.predefinirexos = predefinirexos;
    }
   
    public Integer getCodest() {
        return this.codest;
    }
    
    public void setCodest(Integer codest) {
        this.codest = codest;
    }
    public String getNoms() {
        return this.noms;
    }
    
    public void setNoms(String noms) {
        this.noms = noms;
    }
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }
    public Set getSeances() {
        return this.seances;
    }
    
    public void setSeances(Set seances) {
        this.seances = seances;
    }
    public Set getPredefinirseances() {
        return this.predefinirseances;
    }
    
    public void setPredefinirseances(Set predefinirseances) {
        this.predefinirseances = predefinirseances;
    }
    public Set getPredefinirexos() {
        return this.predefinirexos;
    }
    
    public void setPredefinirexos(Set predefinirexos) {
        this.predefinirexos = predefinirexos;
    }




}


